In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\ky042\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#imporing library for the data integration
import pandas as pd

In [3]:
#Data to series from

marks=[88,99,77,60,69]
std_marks=pd.Series(marks)
print(std_marks)

0    88
1    99
2    77
3    60
4    69
dtype: int64

In [4]:
#convertind data to series
marks=pd.Series([88,99,77,60,69],index=["Math","Science","Engl","Hindi","Geo"])
print(marks)

Math       88
Science    99
Engl       77
Hindi      60
Geo        69
dtype: int64

In [5]:
#Accessing series by index value
print(marks[0:4])

Math       88
Science    99
Engl       77
Hindi      60
dtype: int64

In [6]:
#Updating series by valus
marks['Hindi']=100
print(marks)

Math        88
Science     99
Engl        77
Hindi      100
Geo         69
dtype: int64

In [7]:
#updating series by index numbers
marks[2]=90
print(marks)

Math        88
Science     99
Engl        90
Hindi      100
Geo         69
dtype: int64

C:\Users\ky042\AppData\Local\Temp\ipykernel_15640\1550319244.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks[2]=90

In [8]:
#performing some arithmatic functions(/,+,-,*)

# ADD 
upd_marks=pd.Series([88,99,77,60,69])
print(upd_marks + 5)

0     93
1    104
2     82
3     65
4     74
dtype: int64

In [9]:
# SUBTRACT
upd_marks=pd.Series([88,99,77,60,69])
print(upd_marks - 5)

0    83
1    94
2    72
3    55
4    64
dtype: int64

In [10]:
# MULTIPLY
upd_marks=pd.Series([88,99,77,60,69])
print(upd_marks *5)

0    440
1    495
2    385
3    300
4    345
dtype: int64

In [11]:
#Divide
upd_marks=pd.Series([88,99,77,60,69])
print(upd_marks /5)

0    17.6
1    19.8
2    15.4
3    12.0
4    13.8
dtype: float64

In [12]:
#Identifying missing value in dataset

missing_marks=pd.Series([88,None,77,None,69])
print(missing_marks)

0    88.0
1     NaN
2    77.0
3     NaN
4    69.0
dtype: float64

In [13]:
#handling missing value
missing_marks.fillna(0,inplace=True)
print(missing_marks)

0    88.0
1     0.0
2    77.0
3     0.0
4    69.0
dtype: float64

In [14]:
#handling missing value
missing_marks.fillna(1,inplace=True)
print(missing_marks)

0    88.0
1     0.0
2    77.0
3     0.0
4    69.0
dtype: float64

In [ ]:
#DataFrame - Two dimensional data with Rows & Columns

In [15]:
data={
    "Name":["Akriti","Sakshi","Komal","Shreya","Soni"],
    "Age":[20,21,23,25,26],
    "Trade":["AIPA","CSA","EM","COPA","COSMO"]
}
#Covert the data in 2-D form(DataFrame)
df=pd.DataFrame(data)
print(df)

     Name  Age  Trade
0  Akriti   20   AIPA
1  Sakshi   21    CSA
2   Komal   23     EM
3  Shreya   25   COPA
4    Soni   26  COSMO

In [16]:
df["Trade"]

0     AIPA
1      CSA
2       EM
3     COPA
4    COSMO
Name: Trade, dtype: object

In [17]:
#Multiple columns select
df[["Name","Trade"]]

     Name  Trade
0  Akriti   AIPA
1  Sakshi    CSA
2   Komal     EM
3  Shreya   COPA
4    Soni  COSMO

In [18]:
#Finding by label based integer
df.loc[0]

Name     Akriti
Age          20
Trade      AIPA
Name: 0, dtype: object

In [19]:
df.loc[1]

Name     Sakshi
Age          21
Trade       CSA
Name: 1, dtype: object

In [20]:
df.loc[2]

Name     Komal
Age         23
Trade       EM
Name: 2, dtype: object

In [21]:
df.loc[3]

Name     Shreya
Age          25
Trade      COPA
Name: 3, dtype: object

In [22]:
df.loc[4]

Name      Soni
Age         26
Trade    COSMO
Name: 4, dtype: object

In [ ]:
# Filter Data

In [23]:
#Single condition
df[df["Age"]>25]

   Name  Age  Trade
4  Soni   26  COSMO

In [25]:
#Multiple conditions 
df[(df["Age"]>21) & (df["Trade"]=="COPA") & (df["Name"]=="Shreya")]

     Name  Age Trade
3  Shreya   25  COPA

In [ ]:
#Sorting Data

In [26]:
#Ascending order
df.sort_values(by="Trade")

     Name  Age  Trade
0  Akriti   20   AIPA
3  Shreya   25   COPA
4    Soni   26  COSMO
1  Sakshi   21    CSA
2   Komal   23     EM

In [27]:
#descending order
df.sort_values(by="Name",ascending=False)

     Name  Age  Trade
4    Soni   26  COSMO
3  Shreya   25   COPA
1  Sakshi   21    CSA
2   Komal   23     EM
0  Akriti   20   AIPA

In [ ]:
#handling missing values

In [28]:
data={
    "Name":["Amit","Ajeet","Raj","Vivek","Saurabh"],
    "Marks":[85,None,70,88,90]
}
df=pd.DataFrame(data)

In [29]:
#check null values
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False  False
4  False  False

In [30]:
#Fill null by specify value
df.fillna(70)

      Name  Marks
0     Amit   85.0
1    Ajeet   70.0
2      Raj   70.0
3    Vivek   88.0
4  Saurabh   90.0

In [31]:
#remove null value
df.dropna()

      Name  Marks
0     Amit   85.0
2      Raj   70.0
3    Vivek   88.0
4  Saurabh   90.0

In [32]:
#filll missing valuye t=with average of other values
df["Marks"].fillna(df["Marks"].mean(),inplace=True)

C:\Users\ky042\AppData\Local\Temp\ipykernel_15640\1426630567.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].mean(),inplace=True)

In [33]:
df

      Name  Marks
0     Amit  85.00
1    Ajeet  83.25
2      Raj  70.00
3    Vivek  88.00
4  Saurabh  90.00

In [ ]:
#grouping Data

In [ ]:
data={
    "Trade":["AIPA","AIPA","Cosmo","CSA","COPA","Cosmo","CSA"],
    "Students":[20,20,40,35,30,20,40]
}
df=pd.DataFrame(data)

In [34]:
df

      Name  Marks
0     Amit  85.00
1    Ajeet  83.25
2      Raj  70.00
3    Vivek  88.00
4  Saurabh  90.00

In [ ]:
df.groupby("Trade")["Students"].sum()

In [ ]:
df.groupby("Trade")["Students"].mean()

In [ ]:
df.groupby("Trade")["Students"].count()

In [ ]:
#used for summerizing data
df.groupby("Trade")["Students"].agg(["sum","mean","count"])

In [ ]:
df=pd.read_csv("salesdata.csv")
df